import type { CSSProperties } from "react";
import { FABRICS } from "../_shared/fabrics.generated";

export type RegionId = "bund" | "hose" | "buendchen";

export interface Swatch {
  id: string;
  name: string;
  hex: string;
  /**
   * Optional square, tileable fabric photo (>=512px, ideally 1024px, seamless).
   * When set, the swatch chip renders the photo; hex remains the fallback
   * (and the underlying tint reference for check-mark contrast).
   * Fabric swatches are generated by scripts/bil2455-build-fabric-swatches.mjs.
   */
  textureSrc?: string;
}

/**
 * Region-level flags. `allowsFabrics = true` opts a region into the extra
 * fabric-print swatches (board delivery, BIL-2455). Bündchen/Bänder etc.
 * stay uni — the board explicitly ruled fabrics OUT for those zones.
 */
export interface RegionDef {
  id: RegionId;
  /** URL search-param key */
  param: "bund" | "hose" | "buendchen";
  label: string;
  description: string;
  defaultColor: string;
  allowsFabrics?: boolean;
}

export const REGIONS: readonly RegionDef[] = [
  {
    id: "bund",
    param: "bund",
    label: "Bund",
    description: "Der elastische Bund am oberen Ende der Hose.",
    defaultColor: "petrol",
  },
  {
    id: "hose",
    param: "hose",
    label: "Hose",
    description: "Das Hauptteil der Hose — beide Beine.",
    defaultColor: "cream",
    allowsFabrics: true,
  },
  {
    id: "buendchen",
    param: "buendchen",
    label: "Bündchen",
    description: "Die gefütterten Bündchen am Hosensaum.",
    defaultColor: "petrol",
  },
] as const;

/**
 * Curated Bilulu-Palette in warmen, kinderzimmertauglichen Farbtönen.
 * IDs sind URL-sicher und stabil; bitte beim Erweitern nicht umnummerieren.
 */
export const PALETTE: readonly Swatch[] = [
  { id: "cream", name: "Creme", hex: "#FAF7F2" },
  { id: "sand", name: "Sand", hex: "#E8DDC8" },
  { id: "taupe", name: "Taupe", hex: "#B5A48A" },
  { id: "powder-pink", name: "Puderrosa", hex: "#E8C2C2" },
  { id: "terracotta", name: "Terrakotta", hex: "#C4704A" },
  { id: "rust", name: "Rost", hex: "#7A3318" },
  { id: "mustard", name: "Senfgelb", hex: "#D4A24C" },
  { id: "sage", name: "Salbei", hex: "#A8C5AB" },
  { id: "forest", name: "Tannengrün", hex: "#3F6444" },
  { id: "sky", name: "Himmelblau", hex: "#A8C8D8" },
  { id: "petrol", name: "Petrol", hex: "#5BA8AE" },
  { id: "navy", name: "Marineblau", hex: "#2D3E50" },
] as const;

export { FABRICS };

/**
 * Full lookup covers uni palette AND fabric prints so a share-link that
 * pastes `?hose=stoff-14` resolves regardless of which chip group produced it.
 */
export const SWATCH_BY_ID: Record<string, Swatch> = Object.fromEntries(
  [...PALETTE, ...FABRICS].map((s) => [s.id, s]),
);

/**
 * Which swatches a given region should offer in its picker. Non-hauptteil
 * regions (Bündchen, Halsbund, Ärmelbund, Schleife, Futter) get uni-only —
 * board rule: fabric prints stay on the main body, not on trims.
 */
export function swatchesForRegion(
  region: { allowsFabrics?: boolean },
): readonly Swatch[] {
  return region.allowsFabrics ? [...PALETTE, ...FABRICS] : PALETTE;
}

export function resolveSwatch(id: string | null | undefined, fallback: string): Swatch {
  if (id && SWATCH_BY_ID[id]) return SWATCH_BY_ID[id];
  return SWATCH_BY_ID[fallback] ?? PALETTE[0];
}

/**
 * CSS for the round swatch chip in the picker. When a fabric photo is
 * attached the chip renders the photo (with hex as paint-fallback for slow
 * networks and broken URLs); otherwise the chip is a plain hex fill.
 */
export function swatchChipStyle(swatch: Swatch): CSSProperties {
  if (!swatch.textureSrc) {
    return { backgroundColor: swatch.hex };
  }
  return {
    backgroundColor: swatch.hex,
    backgroundImage: `url(${swatch.textureSrc})`,
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
  };
}

export function resolveColor(id: string | null | undefined, fallback: string): string {
  if (!id) return SWATCH_BY_ID[fallback]?.hex ?? "#FAF7F2";
  return SWATCH_BY_ID[id]?.hex ?? SWATCH_BY_ID[fallback]?.hex ?? "#FAF7F2";
}

export function resolveSwatchId(id: string | null | undefined, fallback: string): string {
  if (id && SWATCH_BY_ID[id]) return id;
  return fallback;
}

/**
 * Read the `hose` swatch id from a URLSearchParams. Falls back to legacy
 * 4-region links/rechts params (shipped in shared configurator links) so old
 * URLs don't crash. When both are present but disagree we prefer `links`;
 * `rechts` is only used when it's the only present value.
 */
export function resolveHoseParam(
  searchParams: URLSearchParams | null,
  fallback: string,
): string {
  if (!searchParams) return fallback;
  const direct = searchParams.get("hose");
  if (direct) return resolveSwatchId(direct, fallback);
  const links = searchParams.get("links");
  if (links) return resolveSwatchId(links, fallback);
  const rechts = searchParams.get("rechts");
  if (rechts) return resolveSwatchId(rechts, fallback);
  return fallback;
}
