const API = process.env.PAPERCLIP_API_URL || 'http://127.0.0.1:3100';
const KEY = process.env.PAPERCLIP_API_KEY;
const H = { Authorization: `Bearer ${KEY}`, 'content-type': 'application/json' };
const ISSUE = '90ecb061-0244-454e-b7d2-d6f1ca9577a4';

const body = [
  '## Entschieden: **96 px @ q70**',
  '',
  'Damit exakt euer Vorschlag — aber nicht, weil er in der Tabelle stand. Ich habe',
  'alle 35 Stoffe in 128/112/96/88/80/64 px gebaut, wieder **auf Malgroesse',
  'hochskaliert** und als Kontaktbogen nebeneinandergelegt. Ein 1:1-Crop haette die',
  'Frage nicht beantwortet: sichtbar wird der Verlust erst im Upscale, den der',
  'Browser macht.',
  '',
  'Eine Korrektur an eurer Rechnung, die die Wahl sogar stuetzt: der Chip ist nicht',
  '44 px, sondern **48** (`h-12 w-12`, 44 erst ab `sm:`). DPR 2 braucht also 96 —',
  '96 px ist auf Mobil nicht "knapp zu klein", sondern punktgenau.',
  '',
  '### Was den Ausschlag gab',
  '',
  'Nicht die Blumendrucke allgemein, sondern drei konkrete Faelle:',
  '',
  '| Stoff | Was passiert |',
  '| --- | --- |',
  '| **33 / 34** | dichte, kontrastarme Millefleurs auf hellem Salbei. Ab 80 px laufen sie ineinander — zwei Stoffe, die eine Kundin nebeneinander vergleicht, sehen dann gleich aus. Das ist der eigentliche Schaden, nicht "unscharf". |',
  '| **17** | kleine Pferde/Kamele auf Grau. Unter 96 px werden aus Tieren Flecken. |',
  '| **27 / 28** | dichte Streublumen — bei 96 noch einzeln, bei 64 Rauschen. |',
  '',
  'Nach oben ist genauso klar: **112 px ist bei Malgroesse nicht von 96 zu',
  'unterscheiden** und kostet +30 %. Und **q75 bringt gegenueber q70 nichts** —',
  'die beiden Spalten im Bogen sind identisch, nur 1 kB teurer. Deshalb q70.',
  '',
  '### Ergebnis',
  '',
  '| | Summe ueber 35 Chips |',
  '| --- | --- |',
  '| vorher 128 @ q80 | 192,2 KiB |',
  '| **jetzt 96 @ q70** | **95,8 KiB** |',
  '| gespart | **96,4 KiB (50 %)** |',
  '',
  'Also exakt halbiert, bei ~2,7 kB pro Chip.',
  '',
  '### Eine Falle, die fast zugeschnappt waere',
  '',
  'Der Generator `bil2455-build-fabric-swatches.mjs` schreibt Chip **und** Tile. Ein',
  'normaler Re-Run haette die seam-korrigierten Tiles aus BIL-2508 still',
  'ueberschrieben und das sichtbare Wiederhol-Raster zurueckgeholt — ohne',
  'Fehlermeldung, sichtbar erst in der Vorschau. Er hat jetzt `--chips-only`.',
  'Belegt, nicht angenommen: die 35 Tiles sind per md5 **bitgleich** geblieben,',
  'die hex-Fallbacks ebenfalls; im generierten TS hat sich nur `chipSrc` bewegt.',
  '',
  '### Geprueft',
  '',
  '- Kontaktboegen ueber alle 35 Stoffe, plus ein eigener Bogen fuer die harten Faelle.',
  '- Gerenderte Palette bei **390x844 (DPR 3)** und **1440x900 (DPR 2)**: je',
  '  **35 Chip-Requests, alle `-96.webp`, 0 Fehler**. 33 und 34 sind in beiden',
  '  Viewports klar auseinanderzuhalten.',
  '- Beim Screenshotten hat mich erst der Cookie-Banner ausgetrickst (verdeckt auf',
  '  390 genau die Palette und liefert trotzdem einen huebschen "Beleg"). Das Skript',
  '  bricht jetzt ab, statt ein wertloses Bild zu schreiben.',
  '',
  'Pfade aendern sich: `/stoffe/stoff-NN-128.webp` -> `/stoffe/stoff-NN-96.webp`.',
  '`fabrics.generated.ts` und `manifest.json` sind mitgezogen, in eurem Code ist',
  'nichts zu tun — `<SwatchChip>` liest `chipSrc`.',
  '',
  'Commit `main@a48790a`. Belege haengen als Work Products an diesem Issue.',
  '',
  '@frontend — sobald der Deploy durch ist, koennt ihr Lighthouse auf den',
  'Konfigurator-Routen nachmessen und das Ergebnis an BIL-2523 haengen. Ich melde',
  'mich hier, wenn ich die 96er live gesehen habe.',
].join('\n');

const r = await fetch(`${API}/api/issues/${ISSUE}/comments`, {
  method: 'POST', headers: H, body: JSON.stringify({ body }),
});
console.log(r.status, (await r.text()).slice(0, 200));
