// AUTO-GENERATED by scripts/bil2455-build-fabric-swatches.mjs
// Do not edit by hand — re-run the script when new fabrics arrive.
//
// textureSrc = 512x512 preview tile (ZoneOverlay, OG card, Merken thumbnail)
// chipSrc    = 128x128 palette chip (swatchChipStyle) — BIL-2493
import type { Swatch } from "../hose/palette";

export const FABRICS: readonly Swatch[] = [
  { id: "stoff-01", name: "Stoff 01", hex: "#783898", textureSrc: "/stoffe/stoff-01.webp", chipSrc: "/stoffe/stoff-01-128.webp" },
  { id: "stoff-02", name: "Stoff 02", hex: "#e8c8d8", textureSrc: "/stoffe/stoff-02.webp", chipSrc: "/stoffe/stoff-02-128.webp" },
  { id: "stoff-03", name: "Stoff 03", hex: "#f8c8f8", textureSrc: "/stoffe/stoff-03.webp", chipSrc: "/stoffe/stoff-03-128.webp" },
  { id: "stoff-04", name: "Stoff 04", hex: "#3858a8", textureSrc: "/stoffe/stoff-04.webp", chipSrc: "/stoffe/stoff-04-128.webp" },
  { id: "stoff-05", name: "Stoff 05", hex: "#e8c8d8", textureSrc: "/stoffe/stoff-05.webp", chipSrc: "/stoffe/stoff-05-128.webp" },
  { id: "stoff-06", name: "Stoff 06", hex: "#f8c8d8", textureSrc: "/stoffe/stoff-06.webp", chipSrc: "/stoffe/stoff-06-128.webp" },
  { id: "stoff-07", name: "Stoff 07", hex: "#e898c8", textureSrc: "/stoffe/stoff-07.webp", chipSrc: "/stoffe/stoff-07-128.webp" },
  { id: "stoff-08", name: "Stoff 08", hex: "#d8d8d8", textureSrc: "/stoffe/stoff-08.webp", chipSrc: "/stoffe/stoff-08-128.webp" },
  { id: "stoff-09", name: "Stoff 09", hex: "#c8c8c8", textureSrc: "/stoffe/stoff-09.webp", chipSrc: "/stoffe/stoff-09-128.webp" },
  { id: "stoff-10", name: "Stoff 10", hex: "#c8c8c8", textureSrc: "/stoffe/stoff-10.webp", chipSrc: "/stoffe/stoff-10-128.webp" },
  { id: "stoff-11", name: "Stoff 11", hex: "#d8d8d8", textureSrc: "/stoffe/stoff-11.webp", chipSrc: "/stoffe/stoff-11-128.webp" },
  { id: "stoff-12", name: "Stoff 12", hex: "#4858a8", textureSrc: "/stoffe/stoff-12.webp", chipSrc: "/stoffe/stoff-12-128.webp" },
  { id: "stoff-13", name: "Stoff 13", hex: "#4878c8", textureSrc: "/stoffe/stoff-13.webp", chipSrc: "/stoffe/stoff-13-128.webp" },
  { id: "stoff-14", name: "Stoff 14", hex: "#a8c8f8", textureSrc: "/stoffe/stoff-14.webp", chipSrc: "/stoffe/stoff-14-128.webp" },
  { id: "stoff-15", name: "Stoff 15", hex: "#e8e8d8", textureSrc: "/stoffe/stoff-15.webp", chipSrc: "/stoffe/stoff-15-128.webp" },
  { id: "stoff-16", name: "Stoff 16", hex: "#b8d8f8", textureSrc: "/stoffe/stoff-16.webp", chipSrc: "/stoffe/stoff-16-128.webp" },
  { id: "stoff-17", name: "Stoff 17", hex: "#b8b8b8", textureSrc: "/stoffe/stoff-17.webp", chipSrc: "/stoffe/stoff-17-128.webp" },
  { id: "stoff-18", name: "Stoff 18", hex: "#98b8e8", textureSrc: "/stoffe/stoff-18.webp", chipSrc: "/stoffe/stoff-18-128.webp" },
  { id: "stoff-19", name: "Stoff 19", hex: "#a8c8f8", textureSrc: "/stoffe/stoff-19.webp", chipSrc: "/stoffe/stoff-19-128.webp" },
  { id: "stoff-20", name: "Stoff 20", hex: "#c88808", textureSrc: "/stoffe/stoff-20.webp", chipSrc: "/stoffe/stoff-20-128.webp" },
  { id: "stoff-21", name: "Stoff 21", hex: "#e8c8c8", textureSrc: "/stoffe/stoff-21.webp", chipSrc: "/stoffe/stoff-21-128.webp" },
  { id: "stoff-22", name: "Stoff 22", hex: "#c8c8c8", textureSrc: "/stoffe/stoff-22.webp", chipSrc: "/stoffe/stoff-22-128.webp" },
  { id: "stoff-23", name: "Stoff 23", hex: "#d8d8d8", textureSrc: "/stoffe/stoff-23.webp", chipSrc: "/stoffe/stoff-23-128.webp" },
  { id: "stoff-24", name: "Stoff 24", hex: "#5878a8", textureSrc: "/stoffe/stoff-24.webp", chipSrc: "/stoffe/stoff-24-128.webp" },
  { id: "stoff-25", name: "Stoff 25", hex: "#385888", textureSrc: "/stoffe/stoff-25.webp", chipSrc: "/stoffe/stoff-25-128.webp" },
  { id: "stoff-26", name: "Stoff 26", hex: "#c89888", textureSrc: "/stoffe/stoff-26.webp", chipSrc: "/stoffe/stoff-26-128.webp" },
  { id: "stoff-27", name: "Stoff 27", hex: "#b8b8b8", textureSrc: "/stoffe/stoff-27.webp", chipSrc: "/stoffe/stoff-27-128.webp" },
  { id: "stoff-28", name: "Stoff 28", hex: "#d8d8c8", textureSrc: "/stoffe/stoff-28.webp", chipSrc: "/stoffe/stoff-28-128.webp" },
  { id: "stoff-29", name: "Stoff 29", hex: "#b8b8b8", textureSrc: "/stoffe/stoff-29.webp", chipSrc: "/stoffe/stoff-29-128.webp" },
  { id: "stoff-30", name: "Stoff 30", hex: "#282838", textureSrc: "/stoffe/stoff-30.webp", chipSrc: "/stoffe/stoff-30-128.webp" },
  { id: "stoff-31", name: "Stoff 31", hex: "#d8d8d8", textureSrc: "/stoffe/stoff-31.webp", chipSrc: "/stoffe/stoff-31-128.webp" },
  { id: "stoff-32", name: "Stoff 32", hex: "#b8b8b8", textureSrc: "/stoffe/stoff-32.webp", chipSrc: "/stoffe/stoff-32-128.webp" },
  { id: "stoff-33", name: "Stoff 33", hex: "#b8b8b8", textureSrc: "/stoffe/stoff-33.webp", chipSrc: "/stoffe/stoff-33-128.webp" },
  { id: "stoff-34", name: "Stoff 34", hex: "#b8b8b8", textureSrc: "/stoffe/stoff-34.webp", chipSrc: "/stoffe/stoff-34-128.webp" },
  { id: "stoff-35", name: "Stoff 35", hex: "#c8c8c8", textureSrc: "/stoffe/stoff-35.webp", chipSrc: "/stoffe/stoff-35-128.webp" },
] as const;
