// Frontend 2026-08-19: BIL-2523 — Befund + Fix + ehrliche Restliste.
const API = process.env.PAPERCLIP_API_URL || 'http://localhost:3100';
const KEY = process.env.PAPERCLIP_API_KEY;
const AUTH = { Authorization: `Bearer ${KEY}`, 'content-type': 'application/json' };
const ISSUE = 'c6283bee-93db-46a0-9812-4835bd1010e7'; // BIL-2523

const body = [
  '## Gefunden: euer LCP-Treiber war kein Designentscheid, sondern ein Encoder-Leck',
  '',
  'Danke fuer die Kontrollmessung — die hat die Sache entschieden. Ich bin eurem',
  'Hinweis nachgegangen (`turban` 4,5s vs. `hose` 2,7s bei gleichem Aufbau) und der',
  'Unterschied liegt genau da, wo ihr ihn vermutet habt: an einem konkreten Asset.',
  '',
  'Lighthouse nennt als LCP-Element `img /konfigurator/turban-foto/base.webp`,',
  'gerendert in einem 330x292-Kasten. Die Phasen dazu:',
  '',
  '| Phase | Zeit | Anteil |',
  '| --- | --- | --- |',
  '| TTFB | 172 ms | 4 % |',
  '| Load Delay | 601 ms | 13 % |',
  '| **Load Time** | **3749 ms** | **80 %** |',
  '| Render Delay | 155 ms | 3 % |',
  '',
  '80 % des LCP war der reine Download dieser einen Datei. Und die war 179 630 B —',
  'gegen 41 980 B bei `hose`. Der Grund steht im WebP-Header:',
  '',
  '```',
  'turban        179630  VP8L   <- lossless',
  'dreieckstuch   69390  VP8L   <- lossless',
  'hose           41980  VP8X + VP8 + ALPH',
  'hose-kurz      27490  VP8X + VP8 + ALPH',
  'muetze         34094  VP8X + VP8 + ALPH',
  'body           12834  VP8X + VP8 + ALPH',
  '```',
  '',
  'Genau zwei Dateien sind verlustfrei — und genau die zwei, durch die',
  '`bil2522-repair-silhouette.mjs` gelaufen ist. Das Skript schreibt sein Ergebnis',
  'mit `{ lossless: true }` ueber die Quelle zurueck. Ueber die Commits:',
  '',
  '| Datei | vor BIL-2522 | nach BIL-2522 |',
  '| --- | --- | --- |',
  '| `turban/base.webp` | 64 254 B (lossy) | 179 630 B (lossless) |',
  '| `dreieckstuch/base.webp` | 28 750 B (lossy) | 69 390 B (lossless) |',
  '',
  'Fuer die **Masken** ist lossless uebrigens richtig und sogar kleiner',
  '(`mask-turban` 23,4 kB lossy -> 20,0 kB lossless) — die habe ich deshalb',
  'angefasst gelassen. Nur das Foto hat es getroffen.',
  '',
  '## Was ich geaendert habe',
  '',
  '**main@6a71350** — `writeInPlace` bekommt die Encoder-Optionen als Parameter,',
  '`base.webp` nutzt jetzt dasselbe `{ quality: 82, alphaQuality: 90 }` wie seine',
  'Builder (`bil2444`/`bil2446-build-*-assets.mjs`), Masken bleiben lossless. Die zwei',
  'ausgelieferten Dateien habe ich neu encodiert.',
  '',
  'Das ist bewusst ein Re-Encode und kein Rebuild: weil die Vorlage **lossless** ist,',
  'sind ihre Pixel exakt die Ausgabe eures Repair-Skripts. q82 darauf ist bit-genau',
  'das, was das Skript mit dem Fix geschrieben haette — es gibt keine zusaetzliche',
  'Lossy-Generation, fuer die ihr bezahlt.',
  '',
  'Die Grenzen standen vor dem Lauf fest (`bil2523-reencode-bases.mjs --check`):',
  '',
  '```',
  'turban        179 630 B -> 55 776 B (-69%)  alphaDelta=0  meanRGB=0,73  maxRGB=15',
  'dreieckstuch   69 390 B -> 20 264 B (-71%)  alphaDelta=0  meanRGB=0,76  maxRGB=20',
  '```',
  '',
  '`alphaDelta=0` ist der Wert, der euch interessieren duerfte: **die',
  'Silhouetten-Reparatur, fuer die BIL-2522 ueberhaupt existiert, ueberlebt den',
  'Encode bit-identisch.** Kein Pixel der Kontur bewegt sich. Nur die Flaeche',
  'innerhalb der Maske gibt im Mittel 0,73 von 255 pro Kanal nach.',
  '`--selftest` verlangt, dass die Alpha-Schranke eine verfaelschte Maske ablehnt.',
  '',
  '**main@fc8e02e** — Ladereihenfolge. Nach dem Encoder-Fix lud `base.webp` (56 kB)',
  'immer noch 3,1 s, weil sie zur exakt selben Millisekunde fertig wurde wie der',
  'letzte JS-Chunk: nichts wurde bevorzugt, die Leitung war gesaettigt. Jetzt hat',
  '`base.webp` `fetchpriority="high"` und die 35 Stoff-Chips der Palette',
  '`fetchpriority="low"`. Dafuer sind die Chips von einem CSS-`background-image` auf',
  'ein echtes `<img>` umgestellt (ein Hintergrundbild laesst sich weder lazy laden',
  'noch priorisieren) — gebuendelt in `<SwatchChip>` fuer alle sechs Konfiguratoren',
  'und das Mobile-Sheet, vorher acht Copy-Paste-Stellen.',
  '',
  '## Ergebnis, live gegen bilulu.de, immer mit Kontrolle',
  '',
  '| Messung (mobile, throttled) | Perf | LCP | TBT | CLS | Transfer |',
  '| --- | --- | --- | --- | --- | --- |',
  '| `turban` Uni — **euer Baseline** | 73 | 4,7 s | 280 ms | 0 | 583 KiB |',
  '| `turban` Uni — nach Encoder-Fix | 79 | 3,9 s | 250 ms | 0 | 462 KiB |',
  '| `turban` Uni — **jetzt** | **87** | **3,0 s** | 220 ms | 0 | 462 KiB |',
  '| `turban` Stoff — vorher | 68 | 3,9 s | 610 ms | 0 | 823 KiB |',
  '| `turban` Stoff — **jetzt** | **73** | **2,8 s** | 760 ms | 0 | 824 KiB |',
  '| `hose` Stoff — **Kontrolle, unveraendert** | 77 | 2,8 s | 560 ms | 0 | 592 KiB |',
  '| `hose` Stoff — jetzt | 78 | 2,9 s | 470 ms | 0 | 592 KiB |',
  '| `dreieckstuch` Stoff — jetzt | 74 | 3,0 s | 610 ms | 0 | 578 KiB |',
  '',
  '`hose` ist die Kontrolle und bewegt sich nicht (77 -> 78, LCP 2,8 -> 2,9 s) — die',
  'Route hatte den Encoder-Bug nie, also darf sie auch nicht profitieren. Genau das',
  'macht die Zahlen auf `turban` glaubwuerdig.',
  '',
  '**Die Luecke aus eurem Ticket ist zu:** `turban` LCP 4,5 s vs. `hose` 2,7 s ist',
  'jetzt `turban` 2,8-3,0 s vs. `hose` 2,9 s. Und die Seite, die ihr ohne eure Ebene',
  'bei **76** gemessen habt, liegt jetzt bei **87**.',
  '',
  '## Was ich NICHT geschafft habe — und warum',
  '',
  'Perf >= 95 ist nicht erreicht, und ich will nicht so tun, als waere das nur noch',
  'Feinschliff. Was uebrig ist:',
  '',
  '1. **Die Palette sind 192 KiB** — 35 Stoff-Chips fuer 44px-Kreise. Das ist der',
  '   groesste verbliebene Posten im LCP-Fenster. `loading="lazy"` bringt hier',
  '   **nichts**, und das habe ich nachgemessen statt vermutet: auf 390x844 und',
  '   1440x900 werden weiterhin alle 35 vor jedem Scroll angefordert, weil Chromes',
  '   Lazy-Schwelle ein Abstand zum Viewport ist (~1250px) und die Palette komplett',
  '   hineinpasst. Groesse/Format der Assets liegen laut eurem Ticket bei euch, also',
  '   liegt das jetzt als **BIL-2524** bei euch — inklusive durchgerechneter Optionen',
  '   (96px @ q70 spart 103 KiB von 192). Ob ein Blumendruck bei 96px noch als',
  '   *dieser* Stoff lesbar ist, entscheidet ihr am Auge, nicht ich an der Dateigroesse.',
  '2. **TBT auf den Stoff-Varianten** (610-760 ms) und `relief.webp` (261 kB auf',
  '   `turban`). Das ist eure Ebene und in BIL-2522 als bewusster Preis abgenommen —',
  '   ich fasse es ohne eure Ansage nicht an. Nur als Datenpunkt: ich messe hier',
  '   mehr als die 420 ms aus eurer Tabelle, das kann Messstreuung sein.',
  '',
  'Ohne 1. sehe ich >= 90 auf den Stoff-Varianten nicht.',
  '',
  '## Belege',
  '',
  '- Lighthouse-JSONs: `apps/e2e/reports/bil2523/*.json` (Baseline, nach Encoder-Fix, final)',
  '- Screenshots 390x844 + 1440x900 live: `apps/e2e/reports/bil2523/turban-{mobile,desktop}-{top,palette,active-chip}.png`',
  '- `apps/e2e/scripts/bil2523-chip-verify.mjs` — gruen auf beiden Viewports gegen live:',
  '  `base` = fetchpriority high, alle 35 Chips = low (DOM-Property, nicht das Attribut),',
  '  alle Chip-Bilder dekodiert, und das Haekchen des aktiven Chips liegt per',
  '  `elementFromPoint` **ueber** der Textur. Der Test behauptet bewusst KEIN Deferral —',
  '  eine Zusicherung, von der wir wissen, dass sie falsch waere, gehoert nicht in einen',
  '  gruenen Test.',
  '- `next build`, `tsc --noEmit`, `next lint` sauber. CLS bleibt 0 auf allen Routen.',
  '',
  '## Naechster Schritt',
  '',
  'Von mir aus ist der Teil, den ihr gemeldet habt, erledigt. Ich haenge mich an',
  'BIL-2524: sobald die Chips kleiner sind, messe ich alle sechs Konfigurator-Routen',
  'nach und haenge das Ergebnis hier an.',
].join('\n');

const r = await fetch(`${API}/api/issues/${ISSUE}/comments`, {
  method: 'POST', headers: AUTH, body: JSON.stringify({ body }),
});
console.log('POST comment ->', r.status);
console.log((await r.text()).slice(0, 300));
